config/routes.rb
Rails.application.routes.draw do
  resources :activities
  resources :sequences
  devise_for :users
  mount Commontator::Engine => '/commontator'
  root 'static_pages#home'
  get 'about' => 'static_pages#about'
  get 'result' => 'activities#result'
  post 'activities/update_difficulties', as: 'update_difficulties'
  get 'select' => 'sequences#select_activities'
  post 'add_selection' => 'sequences#add_selection'
  post 'remove_selection' => 'sequences#remove_selection'
  get 'update_result' => 'sequences#update_result'
  resources :events do
    put :sort, on: :collection
  end
end

app/models/activity.rb
class Activity < ApplicationRecord
    belongs_to :submittor, :class_name => "User",:foreign_key => "user_id"
    has_many :events
    validates :title, :classification, :supplies, :outcomes,
        :setup, :procedure, :modifications, :processing, presence: true
    validates :title, uniqueness: { case_sensitive: false }
    validates :title, length:{ minimum: 2, maximum: 80 }
    
    searchkick
    acts_as_commontable
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:update_difficulties, :edit, :update, :destroy, :create, :new]
  before_action :verify_user, only: [:edit, :update, :destroy]
  
  # GET /activities
  # GET /activities.json
  def index
    @activities = Activity.all
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
  end

  # GET /activities/new
  def new
    @activity = Activity.new
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = Activity.new(activity_params)
    respond_to do |format|
      if @activity.save
        current_user.activities << @activity
        format.html { redirect_to @activity, notice: 'Activity was successfully created.' }
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1
  # PATCH/PUT /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to @activity, notice: 'Activity was successfully updated.' }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity.destroy
    respond_to do |format|
      format.html { redirect_to activities_url, notice: 'Activity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def result
    if params[:search] == ""
      @activities = Activity.search "*"
    else
      @activities = Activity.search params[:search],  page: params[:page], fields: ["title^10", "classification^8", "outcomes^6", "processing" ]
    end
  end

  def update_difficulties
    submitted_physical_difficulty = params[:physicalDifficulty].to_f
    submitted_interpersonal_difficulty = params[:interpersonalDifficulty].to_f
    submitted_emotional_difficulty = params[:emotionalDifficulty].to_f
    @activity = Activity.find(params[:id])
    if @activity.total_votes
      @activity.total_votes += 1
      @activity.physical_difficulty = ((@activity.physical_difficulty * (@activity.total_votes - 1)) + submitted_physical_difficulty / 5) / @activity.total_votes 
      @activity.interpersonal_difficulty = ((@activity.interpersonal_difficulty * (@activity.total_votes - 1)) + submitted_interpersonal_difficulty / 5) / @activity.total_votes
      @activity.emotional_difficulty = ((@activity.emotional_difficulty * (@activity.total_votes - 1)) + submitted_emotional_difficulty / 5) / @activity.total_votes
    else 
      @activity.total_votes = 1
      @activity.physical_difficulty = submitted_physical_difficulty / 5.0
      @activity.interpersonal_difficulty = submitted_interpersonal_difficulty / 5.0
      @activity.emotional_difficulty = submitted_emotional_difficulty / 5.0
    end
    
    @activity.save
    
    respond_to do |format|
      format.js
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_params
      params.require(:activity).permit(:title, :classification, :supplies, :outcomes, :setup, :procedure, :modifications, :processing, :notes)
    end
    
    def verify_user
      @activity = Activity.find(params[:id])
      if (@activity.user_id != current_user.id) && !current_user.admin
        flash[:notice]  = "You do not have permission to do that."
        redirect_to activities_path
      end
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
    def getPhysicalDifficulty
        if @activity.physical_difficulty
            return @activity.physical_difficulty
        else
            return 0
        end
    end
    
    def getInterpersonalDifficulty
        if @activity.interpersonal_difficulty
            return @activity.interpersonal_difficulty
        else
            return 0
        end
    end
    
    def getEmotionalDifficulty
        if @activity.emotional_difficulty
            @activity.emotional_difficulty
        else
            return 0
        end
    end
end

app/views/activities/_activity.html.erb
<tr>
    <td><%= activity.title %></td>
    <td><%= activity.classification %></td>
    <td><%= activity.outcomes %></td>
    <td>
        <%= link_to activity do %>
            <i class="glyphicon glyphicon-book"></i>
        <% end %>
        <%= link_to edit_activity_path(activity) do %>
            <i class="glyphicon glyphicon-pencil"></i>
        <% end %>
        <%= link_to activity, method: :delete, data: { confirm: "Are you sure?" } do %>
            <i class="glyphicon glyphicon-remove"></i>
        <% end %>
    </td>
</tr>

app/views/activities/_form.html.erb
<%= form_for(activity) do |f| %>
  <% if activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
      <% activity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group row">
    <%= f.label :classification , class:"col-sm-2 col-sm-offset-3 form-control-label" %>
    <div class="col-sm-3">
      <%= f.select :classification, ['Ice Breaker', 'Trust/Awareness/Communcation','Problem Solving Initiative'], class:"form-control" %>
    </div>
  </div>
  
  <div class="form-group row">
    <%= f.label :title , class:"col-sm-2 col-sm-offset-3 form-control-label"%>
    <div class="col-sm-3">
      <%= f.text_field :title, class:"form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :supplies , class:"col-sm-2 col-sm-offset-3 form-control-label" %>
    <div class="col-sm-3">
      <%= f.text_field :supplies, class:"form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :outcomes , class:"col-sm-2 col-sm-offset-3 form-control-label" %>
    <div class="col-sm-3">
      <%= f.text_area :outcomes, class:"form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :setup , class:"col-sm-2 col-sm-offset-3 form-control-label" %>
    <div class="col-sm-3">
      <%= f.text_area :setup, class:"form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :procedure , class:"col-sm-2 col-sm-offset-3 form-control-label" %>
    <div class="col-sm-3">
      <%= f.text_area :procedure, class:"form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :modifications , class:"col-sm-2 col-sm-offset-3 form-control-label" %>
    <div class="col-sm-3">
      <%= f.text_area :modifications, class:"form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :processing , class:"col-sm-2 col-sm-offset-3 form-control-label" %>
    <div class="col-sm-3">
      <%= f.text_area :processing, class:"form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :notes, class:"col-sm-2 col-sm-offset-3 form-control-label"  %>
    <div class="col-sm-3">
      <%= f.text_area :notes, class:"form-control" %>
    </div>
  </div>
  
  <div class="form-group row">
    <div class="col-sm-offset-3 col-sm-10">
      <div>
        <%= f.submit class: 'btn btn-success'%>
      </div>
    </div>
  </div>
<% end %>

app/views/activities/_ratings.html.erb
<% if getPhysicalDifficulty <= 0.2 %>
    <strong>Physical:</strong> <%= progress_bar getPhysicalDifficulty, alternative: 'success' %>
<% elsif getPhysicalDifficulty <= 0.4 %>
    <strong>Physical:</strong> <%= progress_bar getPhysicalDifficulty, alternative: 'info' %>
<% elsif getPhysicalDifficulty <= 0.6 %>
    <strong>Physical:</strong> <%= progress_bar getPhysicalDifficulty %>
<% elsif getPhysicalDifficulty <= 0.8 %>
    <strong>Physical:</strong> <%= progress_bar getPhysicalDifficulty, alternative: 'warning' %>
<% else %>
    <strong>Physical:</strong> <%= progress_bar getPhysicalDifficulty, alternative: 'danger' %>
<% end %>

<br>

<% if getInterpersonalDifficulty <= 0.2 %>
    <strong>Interpersonal:</strong> <%= progress_bar getInterpersonalDifficulty, alternative: 'success' %>
<% elsif getInterpersonalDifficulty <= 0.4 %>
    <strong>Interpersonal:</strong> <%= progress_bar getInterpersonalDifficulty, alternative: 'info' %>
<% elsif getInterpersonalDifficulty <= 0.6 %>
    <strong>Interpersonal:</strong> <%= progress_bar getInterpersonalDifficulty %>
<% elsif getInterpersonalDifficulty <= 0.8 %>
    <strong>Interpersonal:</strong> <%= progress_bar getInterpersonalDifficulty, alternative: 'warning' %>
<% elsif getInterpersonalDifficulty > 0.8 %>
    <strong>Interpersonal:</strong> <%= progress_bar getInterpersonalDifficulty, alternative: 'danger' %>
<% end %>

<br>

<% if getEmotionalDifficulty <= 0.2 %>
    <strong>Emotional:</strong> <%= progress_bar getEmotionalDifficulty, alternative: 'success' %>
<% elsif getEmotionalDifficulty <= 0.4 %>
    <strong>Emotional:</strong> <%= progress_bar getEmotionalDifficulty, alternative: 'info' %>
<% elsif getEmotionalDifficulty <= 0.6 %>
    <strong>Emotional:</strong> <%= progress_bar getEmotionalDifficulty %>
<% elsif getEmotionalDifficulty <= 0.8 %>
    <strong>Emotional:</strong> <%= progress_bar getEmotionalDifficulty, alternative: 'warning' %>
<% else %>
    <strong>Emotional:</strong> <%= progress_bar getEmotionalDifficulty, alternative: 'danger' %>
<% end %>

app/views/activities/_submitted.html.erb
Thank you for your input!

app/views/activities/_vote.html.erb
We value your input! Please contribute your experience using the poll below.  
<br>
<div class="form-group row">
    <div class="col-sm-2">
        <strong>Physical Difficulty:</strong>
    </div>
    <div class="col-sm-3">
        <%= select_tag "physical-difficulty-rating", options_for_select([['Not Difficult', 1], ['Easy Difficulty', 2], ['Fairly Difficult', 3], 
                        ['Very Difficult', 4], ['Extremely Difficult', 5]]) %>
    </div>
</div>
<div class="form-group row">
    <div class="col-sm-2">
        <strong>Interpersonal Difficulty:</strong>
    </div>
    <div class="col-sm-3">
        <%= select_tag "interpersonal-difficulty-rating", options_for_select([['Not Difficult', 1], ['Easy Difficulty', 2], ['Fairly Difficult', 3], 
                        ['Very Difficult', 4], ['Extremely Difficult', 5]]) %>
    </div>
</div>
<div class="form-group row">
    <div class="col-sm-2">
        <strong>Emotional Difficulty:</strong>
    </div>
    <div class="col-sm-3">
        <%= select_tag "emotional-difficulty-rating", options_for_select([['Not Difficult', 1], ['Easy Difficulty', 2], ['Fairly Difficult', 3], 
                        ['Very Difficult', 4], ['Extremely Difficult', 5]]) %>
    </div>
</div>

<%= hidden_field_tag('activity-id', @activity.id) %>
<button type="button" class="btn btn-info" id="vote-submit"}>Submit</button>

app/views/activities/edit.html.erb
<h2>Editing Activity</h2>

<%= render 'form', activity: @activity %>

<%= link_to 'Show', @activity %> |
<%= link_to 'Back', activities_path %>

app/views/activities/index.html.erb
<div class="row">
  <div class="col-md-9 col-xs-offset-1">
    <h2>Activities</h2>
    <%= form_tag(result_path, :method => "get", id: "search-form") do %>
      <%= text_field_tag :search, params[:search], placeholder: "Search Activities" %>
      <%= submit_tag "Search", :name => nil %>
    <% end %>
    <table class="table table-hover">
      <thead>
      <tr>
        <th>Title</th>
        <th>Classification</th>
        <th>Outcomes</th>
        <th>Actions</th>
      </tr>
    </thead>
  
    <tbody>
      <% @activities.each do |activity| %>
        <tr>
          <td><%= activity.title %></td>
          <td><%= activity.classification %></td>
          <td><%= activity.outcomes %></td>
          <td>
            <%= link_to activity do %>
              <i class="glyphicon glyphicon-book"></i>
            <% end %>
            <% if user_signed_in? && (activity.user_id == current_user.id || current_user.admin) %>
              <%= link_to edit_activity_path(activity) do %>
                <i class="glyphicon glyphicon-pencil"></i>
              <% end %>
              <%= link_to activity, method: :delete, data: { confirm: "Are you sure?" } do %>
                <i class="glyphicon glyphicon-remove"></i>
              <% end %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Activity', new_activity_path %>
  </div>
</div>

app/views/activities/new.html.erb
<div class="col-sm-9 col-sm-offset-5">
    <h2>New Activity</h2>
</div>

<%= render 'form', activity: @activity %>

<%= link_to 'Back', activities_path %>

app/views/activities/result.html.erb
<div class="row">
  <div class="col-md-9 col-xs-offset-1">
    <h2>Activities</h2>
    <%= form_tag(result_path, :method => "get", id: "search-form") do %>
      <%= text_field_tag :search, params[:search], placeholder: "Search Activities" %>
      <%= submit_tag "Search", :name => nil %>
    <% end %>
  <% if !@activities %>
    Your search returned no results.
  <% else %>
    <table class="table table-hover">
      <thead>
      <tr>
        <th>Title</th>
        <th>Classification</th>
        <th>Outcomes</th>
        <th>Actions</th>
      </tr>
      </thead>
      
      <tbody>
          <%= render @activities %>
      </tbody>
    </table>
  <% end %>  


  <br>
  <%= link_to 'New Activity', new_activity_path %>
  </div>
</div>

app/views/activities/show.html.erb
<div class="col-md-8 col-sm-offset-2">
  <br>
  <div class="row">
    <div class="panel panel-primary">
      <div class="panel-heading"><strong>Basic Info</strong></div>
      <div class="panel-body">
        <strong>Title:</strong> <%= @activity.title %>
        <br>
        <strong>Classification:</strong> <%= @activity.classification %>
      </div>
    </div>
  </div>
  

  <div class="row">
    <div class="panel panel-primary">
      <div class="panel-heading"><strong>Difficulty Ratings</strong></div>
      <div class="panel-body">
        <div id="vote-results">
          <%= render partial: 'ratings' %>
        </div>
        <% if user_signed_in? %>
          <div id="vote-form">
            <%= render partial: 'vote' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  
  <div class="row">
    <div class="panel panel-primary">
      <div class="panel-heading"><strong>Setup</strong></div>
      <div class="panel-body">
        <strong>Supplies:</strong> <%= @activity.supplies %>
        <br>
        <strong>Setup:</strong> <%= @activity.setup %>
      </div>
    </div>
  </div>  

  <div class="row">
    <div class="panel panel-primary">
      <div class="panel-heading"><strong>Procedure</strong></div>
      <div class="panel-body">
        <strong>Procedure:</strong> <%= @activity.procedure %>
      </div>
    </div>
  </div>  

  <div class="row">
    <div class="panel panel-primary">
      <div class="panel-heading"><strong>Outcomes</strong></div>
      <div class="panel-body">
        <strong>Outcomes:</strong> <%= @activity.outcomes %>
        <br>
        <strong>Processing:</strong> <%= @activity.processing %>
      </div>
    </div>
  </div>  

  <div class="row">
    <div class="panel panel-primary">
      <div class="panel-heading"><strong>Notes</strong></div>
      <div class="panel-body">
        <strong>Modifications:</strong> <%= @activity.modifications %>
        <br>
        <strong>Misc. Notes:</strong> <%= @activity.notes %>
      </div>
    </div>
  </div> 
  <%= commontator_thread(@activity) %>
  <%= link_to 'Edit', edit_activity_path(@activity) %> |
  <%= link_to 'Back', activities_path %>
</div>