config/routes.rb
Rails.application.routes.draw do
  resources :activities
  resources :sequences
  devise_for :users
  mount Commontator::Engine => '/commontator'
  root 'static_pages#home'
  get 'about' => 'static_pages#about'
  get 'result' => 'activities#result'
  post 'activities/update_difficulties', as: 'update_difficulties'
  get 'select' => 'sequences#select_activities'
  post 'add_selection' => 'sequences#add_selection'
  post 'remove_selection' => 'sequences#remove_selection'
  get 'update_result' => 'sequences#update_result'
  resources :events do
    put :sort, on: :collection
  end
end

app/views/layouts/_flashes.html.erb
<div class="row" align = center>
    <div class="col-md-6 col-md-offset-3">  
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation", id="navbar">
    <div class="container topnav">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <%= link_to "Facilitate Me", root_url,:class =>"navbar-brand topnav"%>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Activities<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><%= link_to "Create Activity", new_activity_path %></li>
                        <li><%= link_to "Search Activities", activities_path %></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Sequences<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><%= link_to "Create Sequence", new_sequence_path %></li>
                        <li><%= link_to "Search Sequences", sequences_path %></li>
                    </ul>
                </li>
                <% if !user_signed_in? %>
                    <li>
                        <%= link_to "Create Account", new_user_registration_path %>
                    </li>
                    <li>
                        <%= link_to "Log in", new_user_session_path %>
                    </li>
                <% else %>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Profile<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
                            <li><%= link_to "Log Out", destroy_user_session_path, :method => :delete %></li>
                        </ul>
                    </li>
                <% end %>
                <li>
                    <%= link_to "About", about_path %>
                </li>
            </ul>
        </div>
    </div>
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Facilitate Me</title>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  
  <%= render 'layouts/shim' %>
  <%= render 'layouts/header' %>
  <%= render 'layouts/flashes' %>
</head>
<body>
<%= yield %>

</body>
</html>