config/routes.rb
Rails.application.routes.draw do
  resources :activities
  resources :sequences
  devise_for :users
  mount Commontator::Engine => '/commontator'
  root 'static_pages#home'
  get 'about' => 'static_pages#about'
  get 'result' => 'activities#result'
  post 'activities/update_difficulties', as: 'update_difficulties'
  get 'select' => 'sequences#select_activities'
  post 'add_selection' => 'sequences#add_selection'
  post 'remove_selection' => 'sequences#remove_selection'
  get 'update_result' => 'sequences#update_result'
  resources :events do
    put :sort, on: :collection
  end
end

app/models/sequence.rb
class Sequence < ApplicationRecord
    has_many :events
    belongs_to :submittor, :class_name => "User",:foreign_key => "user_id"
    validates :title, presence: true, length: { maximum: 100 }
    validates :description, presence: true, length: { maximum: 100 }
end

app/controllers/sequences_controller.rb
class SequencesController < ApplicationController
  before_action :set_sequence, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:edit, :update, :destroy, :create, :new]
  before_action :verify_user, only: [:edit, :update, :destroy]
  
  def index
    @sequences = Sequence.all
  end
  
  def show
    @sequence = Sequence.find(params[:id])
    @events = @sequence.events.all
  end
  
  def edit
  end

  def new
    @sequence = Sequence.new
  end
  
  def create
    @sequence = Sequence.new(sequence_params)
    respond_to do |format|
      if @sequence.save
        current_user.sequences << @sequence
        format.html { redirect_to select_path(:id => @sequence.id), notice: 'Sequence was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end
  
  def update
    respond_to do |format|
      if @sequence.update(sequence_params)
        format.html { redirect_to @sequence, notice: 'Sequence was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end
 
  def destroy
    @sequence.destroy
    respond_to do |format|
      format.html { redirect_to sequences_url, notice: 'Sequence was successfully destroyed.' }
    end
  end 

  def select_activities
    @sequence = Sequence.find(params[:id])
    @activities = Activity.all
    @events = @sequence.events.all
  end

  def add_selection
    @sequence = Sequence.find(params[:sequence_id])
    @activity = Activity.find(params[:activity_id])
    @event = Event.new(:priority => 1)
    @event.activity = @activity
    @event.sequence = @sequence
    @event.priority = 1
    @event.save
    @events = @sequence.events.all

    respond_to do |format|
      format.js
    end
  end

  def remove_selection
    @sequence = Sequence.find(params[:sequence_id])
    @event = @sequence.events.find(params[:event_id])
    @event.destroy
    @sequence.reload
    @events = @sequence.events.all
    
    respond_to do |format|
      format.js
    end
  end

  def update_result
    @sequence = Sequence.find(params[:sequence_id])
    if params[:search] == ""
      @activities = Activity.search "*"
    else
      @activities = Activity.search params[:search],  page: params[:page], fields: ["title^10", "classification^8", "outcomes^6", "processing" ]
    end
    
    respond_to do |format|
      format.js
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sequence
      @sequence = Sequence.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sequence_params
      params.require(:sequence).permit(:title, :description)
    end
    
    def verify_user
      @sequence = Sequence.find(params[:id])
      if (@sequence.user_id != current_user.id) && !current_user.admin
        flash[:notice]  = "You do not have permission to do that."
        redirect_to sequences_path
      end
    end
end

app/helpers/sequences_helper.rb
module SequencesHelper
end

app/views/sequences/_event.html.erb
<div class='event-box' data-id="<%= event.id %>">
    <%=event.activity.title%>
    <div align='right'>
        <div class="remove-activity", event_id=<%=event.id%>, sequence_id=<%=@sequence.id%>>
            <a href='#', class="glyphicon glyphicon-remove"></a>
        </div>
    </div>
    <hr>
    <%=event.activity.classification %>
</div>

app/views/sequences/_event_list.html.erb
<% if @events.any? %>
    <% @events.each do |event| %>
        <div class='event-box' data-id="<%= event.id %>">
            <%=event.activity.title%>
            <hr>
            <%=event.activity.classification %>
        </div>
    <% end %>
<% else %>
    No activities have been selected.
<% end %>

app/views/sequences/_form.html.erb
<%= form_for(sequence) do |f| %>
  <% if sequence.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sequence.errors.count, "error") %> prohibited this sequence from being saved:</h2>

      <ul>
      <% sequence.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group row">
    <%= f.label :title , class:"col-sm-2 col-sm-offset-3 form-control-label"%>
    <div class="col-sm-3">
      <%= f.text_field :title, class:"form-control" %>
    </div>
  </div>
 
  <div class="form-group row">
    <%= f.label :description , class:"col-sm-2 col-sm-offset-3 form-control-label"%>
    <div class="col-sm-3">
      <%= f.text_field :description, class:"form-control" %>
    </div>
  </div>
  
  <div class="form-group row">
    <div class="col-sm-offset-3 col-sm-10">
      <div>
        <%= f.submit class: 'btn btn-success'%>
      </div>
    </div>
  </div>
<% end %>

app/views/sequences/_results.html.erb
<% if @activities.any? %>
    <table class="table table-hover">
        <thead>
            <tr>
                <th>Title</th>
                <th>Classification</th>
                <th>Outcomes</th>
                <th>Actions</th>
            </tr>
        </thead>
      
        <tbody>
            <% @activities.each do |activity| %>
                <tr>
                    <td><%= activity.title %></td>
                    <td><%= activity.classification %></td>
                    <td><%= activity.outcomes %></td>
                        <td>            
                        <div class="activity-selection", activity_id=<%=activity.id%>, sequence_id=<%=@sequence.id%>>
                            <a href='#', class="glyphicon glyphicon-plus"></a>
                        </div>
                    </td>
                </tr>
            <% end %>
        </tbody>
    </table>
<% else %>
    Your search returned no results
<% end %>

app/views/sequences/edit.html.erb
<div class="col-sm-9 col-sm-offset-5">
    <h2>Edit Sequence</h2>
    <%= link_to 'Select Activities', select_path(:id => @sequence.id), class:'btn btn-primary' %>
</div>
<%= render 'form', sequence: @sequence %>

app/views/sequences/index.html.erb
<div class="row">
  <div class="col-md-9 col-xs-offset-1">
    <h2>Sequences</h2>
    <table class="table table-hover">
      <thead>
      <tr>
        <th>Title</th>
        <th>Description</th>
        <th>Actions</th>
      </tr>
    </thead>
  
    <tbody>
      <% @sequences.each do |sequence| %>
        <tr>
          <td><%= sequence.title %></td>
          <td><%= sequence.description %></td>
          <td>
            <%= link_to sequence do %>
              <i class="glyphicon glyphicon-book"></i>
            <% end %>
            <% if user_signed_in? && (sequence.user_id == current_user.id || current_user.admin) %>
              <%= link_to edit_sequence_path(sequence) do %>
                <i class="glyphicon glyphicon-pencil"></i>
              <% end %>
              <%= link_to sequence, method: :delete, data: { confirm: "Are you sure?" } do %>
                <i class="glyphicon glyphicon-remove"></i>
              <% end %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New sequence', new_sequence_path %>
  </div>
</div>

app/views/sequences/new.html.erb
<div class="col-sm-9 col-sm-offset-5">
    <h2>New Sequence</h2>
</div>

<%= render 'form', sequence: @sequence %>

app/views/sequences/select_activities.html.erb
<div class="row" id="search-activities">
    <div class="col-md-9 col-xs-offset-1">
        <%= hidden_field_tag('sequence-id', @sequence.id) %>
        <h2>Select Activities</h2>
        <button type="button" class="btn btn-success" id="search-submit"}>Search</button>  
        <input type="text" id="search-terms">
        
        <div id="search-results">
            <%= render :partial => 'results' %>
        </div>
        
        <br>
    </div>
</div>

<hr>

<div class="row" id="selected-activities">
    <div class="col-md-6 col-sm-offset-3" align="center">
        <h2>Sequence Events</h2>
    </div>
    <div class="col-md-6 col-sm-offset-3 sortable", id="sequence-activities">
        <%= render @events %>
    </div>
</div>

app/views/sequences/show.html.erb
<div class="row">
    <div class="col-md-6 col-sm-offset-3" align="center">
        <h2><%=@sequence.title%></h2>
        <h5><%=@sequence.description%></h5>
    </div>
    <div class="col-md-6 col-sm-offset-3 sortable", id="sequence-activities">
        <%= render :partial => "event_list" %>
    </div>
</div>